name: run cronjob.py

on: 
  schedule:
    - cron: '35 20 * * 1-5' # At 05:00 on every day-of-week from Monday through Friday
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: checkout repo content
        uses: actions/checkout@v3 # checkout the repository content

      - name: setup python
        uses: actions/setup-python@v3
        with:
          python-version: '3.9' # install the python version needed

      # - uses: browser-actions/setup-chrome@latest
      # - run: chrome --version

      - name: Removing previous chrome instances on runner 
        run: sudo apt purge google-chrome-stable  
        
      - name: install python packages
        run: |
          python -m pip install --upgrade pip
          pip install pip install chromedriver-autoinstaller selenium

      - name: execute py script # run cronjob.py
        run: python cronjob.py

      # - name: commit files
      #   run: |
      #     git config --local user.email "action@github.com"
      #     git config --local user.name "GitHub Action"
      #     git add -A
      #     git diff-index --quiet HEAD || (git commit -a -m "updated files" --allow-empty)

      # - name: push changes
      #   uses: ad-m/github-push-action@v0.6.0
      #   with:
      #     github_token: ${{ secrets.GITHUB_TOKEN }}
      #     branch: main 
        
